name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'
    
    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        # Try to install specific kernel headers, fall back to generic if not available
        if ! sudo apt-get install -y linux-headers-$(uname -r); then
          echo "Specific kernel headers not found, installing generic headers"
          sudo apt-get install -y linux-headers-generic
        fi
        # Install iproute2 for network configuration
        sudo apt-get install -y iproute2
        # Load the TUN module
        sudo modprobe tun
    
    - name: Install npm dependencies
      run: npm ci
    
    - name: Build native addon
      run: |
        # Set environment variable to treat warnings as non-fatal
        export CXXFLAGS="-Wno-error"
        npm run build:addon
    
    - name: Build TypeScript
      run: npm run build
    
    - name: Check IPv6 configuration
      run: |
        echo "Checking IPv6 configuration..."
        ip -6 addr
        sysctl net.ipv6.conf.all.disable_ipv6
        # Ensure IPv6 is enabled
        sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0
        sudo sysctl -w net.ipv6.conf.default.disable_ipv6=0
        sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=0
    
    - name: Run tests
      run: |
        # Check Linux prerequisites
        sudo bash test/check-linux-prereqs.sh
        
        # Run all Mocha tests
        sudo $(which npm) test || {
          echo "Mocha tests failed. Collecting diagnostic information..."
          sudo lsmod | grep tun
          ls -la /dev/net/tun
          ip link
          ip -6 addr
          exit 1
        }
