name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  prepare_matrix:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.generate-matrix.outputs.lts }}
    steps:
    - name: Select all current LTS versions of Node.js
      id: generate-matrix
      uses: msimerson/node-lts-versions@v1

  build-and-test:
    runs-on: ubuntu-latest
    needs:
    - prepare_matrix
    strategy:
      fail-fast: false
      matrix:
        node-version: ${{ fromJSON(needs.prepare_matrix.outputs.versions) }}

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        # Try to install specific kernel headers, fall back to generic if not available
        if ! sudo apt-get install -y linux-headers-$(uname -r); then
          echo "Specific kernel headers not found, installing generic headers"
          sudo apt-get install -y linux-headers-generic
        fi
        # Install iproute2 for network configuration
        sudo apt-get install -y iproute2
        # Load the TUN module
        sudo modprobe tun

    - name: Install npm dependencies
      run: npm install

    - name: Build native addon
      run: |
        # Set environment variable to treat warnings as non-fatal
        export CXXFLAGS="-Wno-error"
        npm run build:addon

    - name: Build TypeScript
      run: npm run build

    - name: Check IPv6 configuration
      run: |
        echo "Checking IPv6 configuration..."
        ip -6 addr
        sysctl net.ipv6.conf.all.disable_ipv6
        # Ensure IPv6 is enabled
        sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0
        sudo sysctl -w net.ipv6.conf.default.disable_ipv6=0
        sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=0

    - name: Run tests
      run: |
        # Check Linux prerequisites
        sudo bash test/check-linux-prereqs.sh

        # Run the test with sudo
        set +e  # Don't exit on error
        sudo node test/test-tuntap.js
        TEST_EXIT_CODE=$?

        # Collect diagnostic information if test fails
        if [ $TEST_EXIT_CODE -ne 0 ]; then
          echo "Test failed with exit code $TEST_EXIT_CODE"
          echo "Collecting diagnostic information..."
          sudo lsmod | grep tun
          ls -la /dev/net/tun
          ip link
          ip -6 addr
        fi

        exit $TEST_EXIT_CODE
