name: Integration Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu-latest, macos-latest]
    uses: ./.github/workflows/shared.yml
    with:
      image: ${{ matrix.image }}
      node-version: lts/*
      test-command: npm run test:integration
      test-name: Integration tests
